
"""esp32mpu6050.ipynb

Automatically generated by Colab.


"""

import tensorflow as tf
from tensorflow.keras import layers , models
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
import pandas as pd

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Input
from tensorflow.keras.utils import to_categorical
from sklearn.preprocessing import LabelEncoder

# Load the dataset
df_400_readings = pd.read_csv(' Your dataset')

# Separate features (X) and labels (y)
X = df_400_readings.drop(['timestamp', 'label'], axis=1) # Drop timestamp as it's not a feature for prediction
y = df_400_readings['label']

# Encode string labels to numeric values
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)

# Get the number of classes from the numerically encoded labels
num_classes = len(label_encoder.classes_)

# Convert numerical labels to one-hot encoding
y_one_hot = to_categorical(y_encoded, num_classes=num_classes)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y_one_hot, test_size=0.2, random_state=42, stratify=y_encoded) # Use y_encoded for stratification

# Define the neural network model
model = Sequential([
    Input(shape=(X_train.shape[1],)), # Explicit Input layer to address the Keras warning
    Dense(64, activation='relu'),
    Dropout(0.2),
    Dense(32, activation='relu'),
    Dropout(0.2),
    Dense(num_classes, activation='softmax') # Output layer with softmax for multi-class classification
])

# Compile the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Display model summary
model.summary()

# Train the model
history = model.fit(X_train, y_train, epochs=20, batch_size=32, validation_split=0.1, verbose=1)

# Evaluate the model on the test set
loss, accuracy = model.evaluate(X_test, y_test, verbose=0)
print(f"\nTest Loss: {loss:.4f}")
print(f"Test Accuracy: {accuracy:.4f}")

print("Model training complete. Evaluation results above.")

"""### Échelonnage des données
Comme mentionné précédemment, il est crucial d'échelonner les données avant de les introduire dans un réseau de neurones. J'utiliserai `StandardScaler` pour standardiser les caractéristiques en supprimant la moyenne et en les échelonnant à la variance unitaire.

Maintenant que les données sont échelonnées, nous devons ré-entraîner et évaluer le modèle en utilisant les données échelonnées. Je vais recréer le modèle pour m'assurer qu'il utilise les données échelonnées.
"""

import tensorflow as tf

# Save the Keras model first
k_model_path = 'neural_network_model.keras'
model.save(k_model_path)
print(f"Keras model saved to {k_model_path}")

# Initialize the TFLite converter
converter = tf.lite.TFLiteConverter.from_keras_model(model)

# Convert the model
tflite_model = converter.convert()

# Save the TFLite model
tflite_model_path = 'neural_network_model.tflite'
with open(tflite_model_path, 'wb') as f:
    f.write(tflite_model)

print(f"TensorFlow Lite model saved to {tflite_model_path}")

